export const colors = {
  background: "#ffffff",
  foreground: "#22262a",
  muted: "#f1f4f6",
  mutedForeground: "#7d8a9a",
  primary: "#1fa85c",
  primaryForeground: "#ffffff",
  border: "#e2e8f0",
  destructive: "#dc2626",
  destructiveForeground: "#ffffff",
  chatBg: "#e8ebe8",
  chatHeader: "#2d8f52",
  chatHeaderForeground: "#ffffff",
  chatInputBg: "#ffffff",
  bubbleSelf: "#d4f0dd",
  bubbleSelfForeground: "#22262a",
  bubbleOther: "#ffffff",
  bubbleOtherForeground: "#22262a",
  recording: "#dc2626",
  audioProgress: "#1fa85c",
  timestamp: "#7d8a9a",
  card: "#ffffff",
};
