export type ThemeTokens = {
  background: string;
  foreground: string;
  muted: string;
  mutedForeground: string;
  primary: string;
  primaryForeground: string;
  primaryTint: string;
  primaryTintStrong: string;
  border: string;
  headerBorder: string;
  destructive: string;
  destructiveForeground: string;
  chatBg: string;
  chatHeader: string;
  chatHeaderForeground: string;
  chatInputBg: string;
  bubbleSelf: string;
  bubbleSelfForeground: string;
  bubbleOther: string;
  bubbleOtherForeground: string;
  recording: string;
  audioProgress: string;
  timestamp: string;
  card: string;
  shadow: string;
  shadowOpacity: number;
  modalBackdrop: string;
  viewerBackdrop: string;
  overlayLight: string;
  accent: string;
  accentForeground: string;
  inputBorder: string;
  inputPlaceholder: string;
  progressTrack: string;
};

export const lightTheme: ThemeTokens = {
  background: "#ffffff",
  foreground: "#22262a",
  muted: "#f1f4f6",
  mutedForeground: "#7d8a9a",
  primary: "#1fa85c",
  primaryForeground: "#ffffff",
  primaryTint: "rgba(31,168,92,0.10)",
  primaryTintStrong: "rgba(31,168,92,0.20)",
  border: "#e2e8f0",
  headerBorder: "#d6dde4",
  destructive: "#dc2626",
  destructiveForeground: "#ffffff",
  chatBg: "#e8ebe8",
  chatHeader: "#2d8f52",
  chatHeaderForeground: "#ffffff",
  chatInputBg: "#ffffff",
  bubbleSelf: "#d4f0dd",
  bubbleSelfForeground: "#22262a",
  bubbleOther: "#ffffff",
  bubbleOtherForeground: "#22262a",
  recording: "#dc2626",
  audioProgress: "#1fa85c",
  timestamp: "#7d8a9a",
  card: "#ffffff",
  shadow: "#000000",
  shadowOpacity: 0.08,
  modalBackdrop: "rgba(0,0,0,0.40)",
  viewerBackdrop: "rgba(0,0,0,0.94)",
  overlayLight: "rgba(255,255,255,0.14)",
  accent: "#7c3aed",
  accentForeground: "#ffffff",
  inputBorder: "#e2e8f0",
  inputPlaceholder: "#9aa5b1",
  progressTrack: "rgba(0,0,0,0.08)",
};

export const darkTheme: ThemeTokens = {
  background: "#0f1417",
  foreground: "#e6ebef",
  muted: "#1a2026",
  mutedForeground: "#9aa5b1",
  primary: "#34c47a",
  primaryForeground: "#07120c",
  primaryTint: "rgba(52,196,122,0.16)",
  primaryTintStrong: "rgba(52,196,122,0.28)",
  border: "#232b32",
  headerBorder: "#2a333b",
  destructive: "#f87171",
  destructiveForeground: "#1a0a0a",
  chatBg: "#0b0f12",
  chatHeader: "#1a3a28",
  chatHeaderForeground: "#ffffff",
  chatInputBg: "#1a2026",
  bubbleSelf: "#1f4d33",
  bubbleSelfForeground: "#e6ebef",
  bubbleOther: "#1f2933",
  bubbleOtherForeground: "#e6ebef",
  recording: "#f87171",
  audioProgress: "#34c47a",
  timestamp: "#8a95a1",
  card: "#161c21",
  shadow: "#000000",
  shadowOpacity: 0.5,
  modalBackdrop: "rgba(0,0,0,0.55)",
  viewerBackdrop: "rgba(0,0,0,0.94)",
  overlayLight: "rgba(255,255,255,0.10)",
  accent: "#a78bfa",
  accentForeground: "#1a0f2e",
  inputBorder: "#2a333b",
  inputPlaceholder: "#6b7682",
  progressTrack: "rgba(255,255,255,0.10)",
};
